apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: backend-ventas
        image: 691743845927.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: endpoint
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ventas_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas-service
  namespace: default
spec:
  selector:
    app: backend-ventas
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
